# Generated by Django 5.1.7 on 2025-03-08 02:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('brend', models.CharField(blank=True, max_length=255, null=True)),
                ('narx1', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('narx2', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('miqdor', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('olchov', models.CharField(choices=[('dona', 'dona'), ('blok', 'blok'), ('kg', 'kg'), ('gram', 'gram'), ('tonna', 'tonna'), ('quti', 'quti'), ('litr', 'litr'), ('qop', 'qop'), ('m', 'm'), ('m²', 'm²'), ('sm', 'sm'), ('km', 'km')], max_length=20)),
                ('sana', models.DateTimeField()),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('dokon', models.CharField(blank=True, max_length=255, null=True)),
                ('manzil', models.TextField(blank=True, null=True)),
                ('telefon', models.CharField(max_length=15)),
                ('qarz', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bolim')),
            ],
        ),
    ]
